### ISSUE TITLE
CSS up widgets 

### ISSUE THREAD

**Issue by lewis150193** [lewis150193/dash-board#3]
Add some CSS to widgets to make them look nicer (Maybe a border and background for each

**Comment by Haddassah** [comment]
How can I contribute? Can you give me access or create me a branch?

**Comment by lewis150193** [comment]
Any CSS enhancements are welcome, you can also create a widget if you like. 

You can contribute but forking the project, creating a branch the opening a PR

**Comment by cluzier** [comment]
pull request made for this issue 👍
